name: sample_size_simu_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip
  - pip:
      - scikit-learn
      - scipy
      - statsmodels
      - matplotlib
      - customtkinter
      - typing
      - tabulate
